
CXX=g++-8
CXXFLAGS=-lpthread -std=c++17 -g -lstdc++fs

parallel_experiment : parallel_experiment.cpp
	$(CXX) -g parallel_experiment.cpp $(CXXFLAGS) -o parallel_experiment

clean :
	rm parallel_experiment